### ISSUE TITLE
Feedbacks from Tim

### ISSUE THREAD

**Issue by gavinfish** [Azure/azure-artifact-manager-plugin#8]
Thanks @timja for testing out this plugin and giving feedback.
I list all the questions here so  that we can follow up and have it done.

**Comment by gavinfish** [comment]
Details:

1. Is it intended that you can add multiple cloud artifact storage, it seems to pick first one?

2. For the account name help text when creating the credential is azure.microsoft.com the intended link for the portal and not portal.azure.com?

3. The add credential popup from /configure opens with the credential type set to username / password, is it possible to have it set to blob storage / only populate blob storage?

4. The pipeline output is quite verbose is all of it needed?
```
Archiving artifacts
MicrosoftAzureStorage - Container name: builds
MicrosoftAzureStorage - share name: null
MicrosoftAzureStorage - File path: blank
MicrosoftAzureStorage - Virtual path: test/4/artifacts/
MicrosoftAzureStorage - Exclude path: null
MicrosoftAzureStorage - Uploading files to Microsoft Azure
MicrosoftAzureStorage - Need uploaded/archived file count = 1
Uploaded to file storage with uri http://timtempdiag.blob.core.windows.net/builds/test/4/artifacts/blank in 00:00:00.033 (HH:mm:ss.S)
```

5. Microsoft Azure Storage Account configuration (step 1 in docs) seems unneeded, adding a new credential through the cloud artifact storage has the same effect and seems more natural

6. Would be good to add a configuration as code example and unit test covering it
```
credentials:
system:
 domainCredentials:
 - credentials:
   - azure:
       blobEndpointURL: "http://blob.core.windows.net/"
       description: "Blob store for artifacts"
       id: "blob-store"
       scope: GLOBAL
       storageAccountName: "accountname"
       storageKey: "thekey"
unclassified:
artifactManager:
 artifactManagerFactories:
 - azure:
     config:
       container: "builds"
       storageCredentialId: "blob-store"
```

7. Seems to be a bug with the log message on stash
Says stashed 2 files but I've only stashed 1:
```
[Pipeline] stash
Stashed 2 file(s) to builds
MicrosoftAzureStorage - Container name: builds
MicrosoftAzureStorage - share name: null
MicrosoftAzureStorage - File path: file-2.tgz
MicrosoftAzureStorage - Virtual path: test/4/stashes/
MicrosoftAzureStorage - Exclude path: null
MicrosoftAzureStorage - Uploading files to Microsoft Azure
MicrosoftAzureStorage - Need uploaded/archived file count = 1
Uploaded to file storage with uri http://timtempdiag.blob.core.windows.net/builds/test/4/stashes/file-2.tgz in 00:00:00.090 (HH:mm:ss.S)
MicrosoftAzureStorage - Uploaded/archived file count = 1
```
Pipeline:
```
node {
    sh "touch blank file-2"
    archiveArtifacts 'blank'
    stash "file-2"
    sleep 2
    unstash "file-2"
}
```

8. Archived artifacts don't seem to be showing up in the classic view or blueocean
